project_id = "phmhzbmlszbontpfeddk"

[functions.create-checkout]
verify_jwt = false

[functions.create-embedded-checkout]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.generate-report]
verify_jwt = false

[functions.generate-pdf]
verify_jwt = false

[functions.send-email]
verify_jwt = false
